### ISSUE TITLE
Running files in colab

### ISSUE THREAD

**Issue by linubajy** [rohankumar0002/extractAnswer-wikipedia#1]
In what order do I run these files?Is it necessary to run all the files?

**Comment by rohankumar0002** [comment]
Run read_comprehension_with_wiki_Ngram_pun_parallel.py

**Comment by rohankumar0002** [comment]
It wont't run on colab, as it's a flask app. Run it on your local system. It doesn't require GPU. 

If you want to run it on colab then comment the flask part in the read_comprehension_with_wiki_Ngram_pun_parallel.py and use it as library. Take reference from the flask part of the code.

**Comment by linubajy** [comment]
Thanks a lot!😊

**Comment by linubajy** [comment]
Could u please send the reference papers you have used for this project?

**Comment by rohankumar0002** [comment]
I don't have any research paper.

**Comment by linubajy** [comment]
Hi
I would like to add an audio button that reads the answer.I could play it
locally but the button isn't visible when hosted.So where do I store the
MP3 file?I think we're using WSGI server right?
