### ISSUE TITLE
Displaying JSON file

### ISSUE THREAD

**Issue by linubajy** [rohankumar0002/extractAnswer-wikipedia#2]
![IMG-20200313-WA0003](https://user-images.githubusercontent.com/62143318/76677833-e8c8f400-65f8-11ea-9a39-08aed2a9a6df.jpeg)

I executed the file read_comprehension_with_wiki_Ngram_pun_parallel.py but it only produced a page as shown.
How exactly do I get to run the html files QnA and results?

**Comment by rohankumar0002** [comment]
It's get request. In query string, pass question parameter.

**Comment by rohankumar0002** [comment]
question = request.args.get('question')
topic = request.args.get('topic')
passage = request.args.get('passage')

These are three query parameters. Question is mandatary to pass.
Topic and passage are optional.

**Comment by Sin-Bad** [comment]
where do I ask the questions ?

**Comment by rohankumar0002** [comment]
In question parameters.
http://xyz.ngrok.io/?question=your question

**Comment by Sin-Bad** [comment]
Thanks it works

**Comment by rohankumar0002** [comment]
Cool
